/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conteopalabras;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class FrmArchivo extends javax.swing.JFrame {

    /**
     * Creates new form FrmArchivo
     */
    
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de texto", "txt");
    private File archivoLeer;
    private LeerArchivo leerArchivo = new LeerArchivo();
    public FrmArchivo() {
        initComponents();
        this.setLocationRelativeTo(null);
        fcSA.setFileFilter(filter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgFC = new javax.swing.JDialog();
        fcSA = new javax.swing.JFileChooser();
        scrlResultado = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        lblRuta = new java.awt.Label();
        btnSA = new java.awt.Button();
        btnCalcular = new java.awt.Button();
        btnCancelar = new java.awt.Button();

        dlgFC.setMinimumSize(new java.awt.Dimension(650, 450));

        fcSA.setName("Seleccionar Archivo"); // NOI18N
        fcSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcSAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgFCLayout = new javax.swing.GroupLayout(dlgFC.getContentPane());
        dlgFC.getContentPane().setLayout(dlgFCLayout);
        dlgFCLayout.setHorizontalGroup(
            dlgFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgFCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fcSA, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgFCLayout.setVerticalGroup(
            dlgFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgFCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fcSA, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fcSA.getAccessibleContext().setAccessibleName("flArchivo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar texto manualmente");

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palabra", "Repeticiones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultado.setName("TblManual"); // NOI18N
        scrlResultado.setViewportView(tblResultado);
        if (tblResultado.getColumnModel().getColumnCount() > 0) {
            tblResultado.getColumnModel().getColumn(1).setResizable(false);
        }

        lblRuta.setText("Ruta.");

        btnSA.setLabel("Seleccionar archivo");
        btnSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAActionPerformed(evt);
            }
        });

        btnCalcular.setLabel("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnCancelar.setActionCommand("Cancelar");
        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRuta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                    .addComponent(scrlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRuta.getAccessibleContext().setAccessibleName("lblRuta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAActionPerformed
        dlgFC.setVisible(true);        
    }//GEN-LAST:event_btnSAActionPerformed

    private void fcSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcSAActionPerformed
       JFileChooser sArchivo = (JFileChooser)evt.getSource();
       String comando = evt.getActionCommand();
       
       if (comando.equals(JFileChooser.APPROVE_SELECTION)){
           File archivoSeleccionado = sArchivo.getSelectedFile();
           archivoLeer = archivoSeleccionado;
           lblRuta.setText(archivoSeleccionado.getAbsolutePath());
           dlgFC.dispose();
       }else if (comando.equals(JFileChooser.CANCEL_SELECTION)) {
           dlgFC.dispose();
       }
    }//GEN-LAST:event_fcSAActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrecuenciaPalabras obj = new FrecuenciaPalabras();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)tblResultado.getModel();
        if (archivoLeer.canRead() && lblRuta.getText() != "Ruta.")
        {
            String contenidoTexto =  leerArchivo.AbrirTexto(archivoLeer);
            ProcesarTexto textoProcesar = new ProcesarTexto(contenidoTexto);
            textoProcesar.AdaptarTexto();
            textoProcesar.FrecuenciaPalabras(tblResultado);
        }        
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCalcular;
    private java.awt.Button btnCancelar;
    private java.awt.Button btnSA;
    private javax.swing.JDialog dlgFC;
    private javax.swing.JFileChooser fcSA;
    private java.awt.Label lblRuta;
    private javax.swing.JScrollPane scrlResultado;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
}
